# Generated by Django 5.2.7 on 2025-10-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
